/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PropelRouteImport } from './routes/propel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropelProjectsRouteImport } from './routes/propel.projects'
import { Route as PropelDashboardRouteImport } from './routes/propel.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PropelRoute = PropelRouteImport.update({
  id: '/propel',
  path: '/propel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropelProjectsRoute = PropelProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PropelRoute,
} as any)
const PropelDashboardRoute = PropelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PropelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/propel': typeof PropelRouteWithChildren
  '/signup': typeof SignupRoute
  '/propel/dashboard': typeof PropelDashboardRoute
  '/propel/projects': typeof PropelProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/propel': typeof PropelRouteWithChildren
  '/signup': typeof SignupRoute
  '/propel/dashboard': typeof PropelDashboardRoute
  '/propel/projects': typeof PropelProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/propel': typeof PropelRouteWithChildren
  '/signup': typeof SignupRoute
  '/propel/dashboard': typeof PropelDashboardRoute
  '/propel/projects': typeof PropelProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/propel'
    | '/signup'
    | '/propel/dashboard'
    | '/propel/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/propel'
    | '/signup'
    | '/propel/dashboard'
    | '/propel/projects'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/propel'
    | '/signup'
    | '/propel/dashboard'
    | '/propel/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PropelRoute: typeof PropelRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propel': {
      id: '/propel'
      path: '/propel'
      fullPath: '/propel'
      preLoaderRoute: typeof PropelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propel/projects': {
      id: '/propel/projects'
      path: '/projects'
      fullPath: '/propel/projects'
      preLoaderRoute: typeof PropelProjectsRouteImport
      parentRoute: typeof PropelRoute
    }
    '/propel/dashboard': {
      id: '/propel/dashboard'
      path: '/dashboard'
      fullPath: '/propel/dashboard'
      preLoaderRoute: typeof PropelDashboardRouteImport
      parentRoute: typeof PropelRoute
    }
  }
}

interface PropelRouteChildren {
  PropelDashboardRoute: typeof PropelDashboardRoute
  PropelProjectsRoute: typeof PropelProjectsRoute
}

const PropelRouteChildren: PropelRouteChildren = {
  PropelDashboardRoute: PropelDashboardRoute,
  PropelProjectsRoute: PropelProjectsRoute,
}

const PropelRouteWithChildren =
  PropelRoute._addFileChildren(PropelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PropelRoute: PropelRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
